version: "3.6"

x-variables:
    common_build_args: &common_build_args
        www_data_uid: 1000
        www_data_gid: 1000

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                <<: *common_build_args
        volumes:
            - .:/var/www/html
        ports:
            - "8080:8080"
